apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - configmap-prometheus.yaml
  - configmap-tempo.yaml
  - configmap-loki.yaml
  - configmap-otel-collector.yaml
  - configmap-grafana-datasources.yaml
  - prometheus.yaml
  - tempo.yaml
  - loki.yaml
  - otel-collector.yaml
  - grafana.yaml
